-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 21:02:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `db_ecommerce` ;

-- -----------------------------------------------------
-- Table `db_ecommerce`.`tb_marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ecommerce`.`tb_marcas` ;

CREATE TABLE IF NOT EXISTS `db_ecommerce`.`tb_marcas` (
  `idtb_marcas` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idtb_marcas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ecommerce`.`tb_produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ecommerce`.`tb_produtos` ;

CREATE TABLE IF NOT EXISTS `db_ecommerce`.`tb_produtos` (
  `id_produto` INT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` DECIMAL NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `tb_marcas_idtb_marcas` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `fk_tb_produtos_tb_marcas_idx` (`tb_marcas_idtb_marcas` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_marcas`
    FOREIGN KEY (`tb_marcas_idtb_marcas`)
    REFERENCES `db_ecommerce`.`tb_marcas` (`idtb_marcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `db_ecommerce`.`tb_marcas` (`marca`) VALUES ('Amazon');
INSERT INTO `db_ecommerce`.`tb_marcas` (`marca`) VALUES ('Otto');
INSERT INTO `db_ecommerce`.`tb_marcas` (`marca`) VALUES ('Ebay');
INSERT INTO `db_ecommerce`.`tb_marcas` (`marca`) VALUES ('JD');
select * from tb_marcas;
INSERT INTO `db_ecommerce`.`tb_produtos` (`nome`, `preco`, `tipo`, `tb_marcas_idtb_marcas`) VALUES ('Celular', '200', 'Samsung', '1');
INSERT INTO `db_ecommerce`.`tb_produtos` (`nome`, `preco`, `tipo`, `tb_marcas_idtb_marcas`) VALUES ('Notbook', '4000', 'LG', '2');
INSERT INTO `db_ecommerce`.`tb_produtos` (`nome`, `preco`, `tipo`, `tb_marcas_idtb_marcas`) VALUES ('Iphone', '5000', 'Apple', '3');
INSERT INTO `db_ecommerce`.`tb_produtos` (`nome`, `preco`, `tipo`, `tb_marcas_idtb_marcas`) VALUES ('Roupa', '200', 'Zara', '2');
INSERT INTO `db_ecommerce`.`tb_produtos` (`nome`, `preco`, `tipo`, `tb_marcas_idtb_marcas`) VALUES ('Pneu', '300', 'Aro 13', '1');
INSERT INTO `db_ecommerce`.`tb_produtos` (`nome`, `preco`, `tipo`, `tb_marcas_idtb_marcas`) VALUES ('Garrafinha', '20', 'RL', '2');
INSERT INTO `db_ecommerce`.`tb_produtos` (`nome`, `preco`, `tipo`, `tb_marcas_idtb_marcas`) VALUES ('Fone', '100', 'Sony', '1');
select * from tb_produtos

