-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 21:26:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_escola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_escola` DEFAULT CHARACTER SET utf8 ;
USE `db_escola` ;

-- -----------------------------------------------------
-- Table `db_escola`.`tb_periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_escola`.`tb_periodo` ;

CREATE TABLE IF NOT EXISTS `db_escola`.`tb_periodo` (
  `idtb_periodo` INT NOT NULL AUTO_INCREMENT,
  `turno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_periodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_escola`.`tb_serie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_escola`.`tb_serie` ;

CREATE TABLE IF NOT EXISTS `db_escola`.`tb_serie` (
  `idtb_serie` INT NOT NULL AUTO_INCREMENT,
  `serie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_serie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_escola`.`tb_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_escola`.`tb_aluno` ;

CREATE TABLE IF NOT EXISTS `db_escola`.`tb_aluno` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nota` DECIMAL(10,2) NOT NULL,
  `tb_periodo_idtb_periodo` INT NOT NULL,
  `tb_serie_idtb_serie` INT NOT NULL,
  PRIMARY KEY (`id_aluno`),
  INDEX `fk_tb_aluno_tb_periodo_idx` (`tb_periodo_idtb_periodo` ASC) VISIBLE,
  INDEX `fk_tb_aluno_tb_serie1_idx` (`tb_serie_idtb_serie` ASC) VISIBLE,
  CONSTRAINT `fk_tb_aluno_tb_periodo`
    FOREIGN KEY (`tb_periodo_idtb_periodo`)
    REFERENCES `db_escola`.`tb_periodo` (`idtb_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_aluno_tb_serie1`
    FOREIGN KEY (`tb_serie_idtb_serie`)
    REFERENCES `db_escola`.`tb_serie` (`idtb_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('Maternal');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('Jardim I');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('Jardim II');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('Jardim III');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('1º ano');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('2ºano');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('3ºano');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('4ºano');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('5º ano');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('6º ano');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('7º ano');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('8ºano');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('9ºano');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('1ºEM');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('2ºEM');
INSERT INTO `db_escola`.`tb_serie` (`serie`) VALUES ('3ºEM');
select * from tb_serie;
INSERT INTO `db_escola`.`tb_periodo` (`turno`) VALUES ('Matutino');
INSERT INTO `db_escola`.`tb_periodo` (`turno`) VALUES ('Vespertino');
INSERT INTO `db_escola`.`tb_periodo` (`turno`) VALUES ('Noturno');
select *from tb_periodo;
INSERT INTO `db_escola`.`tb_aluno` (`nome`, `nota`, `tb_periodo_idtb_periodo`, `tb_serie_idtb_serie`) VALUES ('Roberto', '7', '1', '13');
INSERT INTO `db_escola`.`tb_aluno` (`nome`, `nota`, `tb_periodo_idtb_periodo`, `tb_serie_idtb_serie`) VALUES ('Sther', '10', '2', '1');
INSERT INTO `db_escola`.`tb_aluno` (`nome`, `nota`, `tb_periodo_idtb_periodo`, `tb_serie_idtb_serie`) VALUES ('Caio', '8', '1', '12');
INSERT INTO `db_escola`.`tb_aluno` (`nome`, `nota`, `tb_periodo_idtb_periodo`, `tb_serie_idtb_serie`) VALUES ('Karla', '5', '1', '10');
INSERT INTO `db_escola`.`tb_aluno` (`nome`, `nota`, `tb_periodo_idtb_periodo`, `tb_serie_idtb_serie`) VALUES ('Fernanda', '9', '2', '4');
INSERT INTO `db_escola`.`tb_aluno` (`nome`, `nota`, `tb_periodo_idtb_periodo`, `tb_serie_idtb_serie`) VALUES ('Luis', '8', '2', '8');
INSERT INTO `db_escola`.`tb_aluno` (`nome`, `nota`, `tb_periodo_idtb_periodo`, `tb_serie_idtb_serie`) VALUES ('Rafa', '4', '3', '11');
INSERT INTO `db_escola`.`tb_aluno` (`nome`, `nota`, `tb_periodo_idtb_periodo`, `tb_serie_idtb_serie`) VALUES ('Diego', '6', '1', '5');
select * from tb_aluno
