-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 19:50:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tb_empresa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tb_empresa` (
  `idtb_empresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(15) NULL,
  `cpf` INT(11) NOT NULL,
  `idade` INT(100) NOT NULL,
  `salario` DECIMAL NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_empresa`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO `mydb`.`tb_empresa` (`nome`, `cpf`, `idade`, `salario`, `cargo`) VALUES ('Kevelly', '1111111', '21', '5000', 'Dev');
INSERT INTO `mydb`.`tb_empresa` (`nome`, `cpf`, `idade`, `salario`, `cargo`) VALUES ('Roberto', '2222222', '30', '1500', 'estagiario');
INSERT INTO `mydb`.`tb_empresa` (`nome`, `cpf`, `idade`, `salario`, `cargo`) VALUES ('Carol', '444444', '32', '4000', 'Auxiliar');
INSERT INTO `mydb`.`tb_empresa` (`nome`, `cpf`, `idade`, `salario`, `cargo`) VALUES ('Daniel', '4444444444', '40', '12000', 'SG');
INSERT INTO `mydb`.`tb_empresa` (`nome`, `cpf`, `idade`, `salario`, `cargo`) VALUES ('Karla', '666666', '30', '40000', 'Diretor');


select * from tb_empresa;
