-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 19:44:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cidade_das_carnes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cidade_das_carnes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cidade_das_carnes` DEFAULT CHARACTER SET utf8 ;
USE `db_cidade_das_carnes` ;

-- -----------------------------------------------------
-- Table `db_cidade_das_carnes`.`tb_categoria2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cidade_das_carnes`.`tb_categoria2` ;

CREATE TABLE IF NOT EXISTS `db_cidade_das_carnes`.`tb_categoria2` (
  `id_categoria2` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `codigo` INT NOT NULL,
  PRIMARY KEY (`id_categoria2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cidade_das_carnes`.`tb_produto3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cidade_das_carnes`.`tb_produto3` ;

CREATE TABLE IF NOT EXISTS `db_cidade_das_carnes`.`tb_produto3` (
  `id_produto3` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DECIMAL NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `fk_categoria2_fk_produto3` INT NOT NULL,
  PRIMARY KEY (`id_produto3`),
  INDEX `fk_tb_produto3_tb_categoria2_idx` (`fk_categoria2_fk_produto3` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto3_tb_categoria2`
    FOREIGN KEY (`fk_categoria2_fk_produto3`)
    REFERENCES `db_cidade_das_carnes`.`tb_categoria2` (`id_categoria2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- select *from tb_categoria2
INSERT INTO `db_cidade_das_carnes`.`tb_categoria2` (`tipo`, `codigo`) VALUES ('Carne Branca', '1');
INSERT INTO `db_cidade_das_carnes`.`tb_categoria2` (`tipo`, `codigo`) VALUES ('Carne vermelha', '2');
INSERT INTO `db_cidade_das_carnes`.`tb_categoria2` (`tipo`, `codigo`) VALUES ('Verduras', '3');
INSERT INTO `db_cidade_das_carnes`.`tb_produto3` (`nome`, `valor`, `marca`, `fk_categoria2_fk_produto3`) VALUES ('Filé', '60.00', 'Friboi', '2');
INSERT INTO `db_cidade_das_carnes`.`tb_produto3` (`nome`, `valor`, `marca`, `fk_categoria2_fk_produto3`) VALUES ('Asas', '30', 'Sadia', '1');
INSERT INTO `db_cidade_das_carnes`.`tb_produto3` (`nome`, `valor`, `marca`, `fk_categoria2_fk_produto3`) VALUES ('Tomate', '2.00', 'Quero', '3');
INSERT INTO `db_cidade_das_carnes`.`tb_produto3` (`nome`, `valor`, `marca`, `fk_categoria2_fk_produto3`) VALUES ('Picanha', '80.00', 'Swift', '2');
INSERT INTO `db_cidade_das_carnes`.`tb_produto3` (`nome`, `valor`, `marca`, `fk_categoria2_fk_produto3`) VALUES ('Linguiça', '20.00', 'Sadia', '2');
INSERT INTO `db_cidade_das_carnes`.`tb_produto3` (`nome`, `valor`, `marca`, `fk_categoria2_fk_produto3`) VALUES ('Peito de Frango', '15.00', 'Perdigão', '1');
INSERT INTO `db_cidade_das_carnes`.`tb_produto3` (`nome`, `valor`, `marca`, `fk_categoria2_fk_produto3`) VALUES ('Cebola', '5.00', '-----', '3');
INSERT INTO `db_cidade_das_carnes`.`tb_produto3` (`nome`, `valor`, `marca`, `fk_categoria2_fk_produto3`) VALUES ('Maminha', '7.00', 'Friboi', '2');
 -- select *from tb_categoria2
-- select * from tb_produto3 where valor >50
-- select * from tb_produto3 where valor BETWEEN 3 and 60
-- select * from tb_produto3 where nome and marca like '%c%'
 -- select tb_categoria2.tipo, tb_categoria2.codigo, tb_produto3.nome, tb_produto3.valor, tb_produto3.marca from tb_produto3 inner join tb_categoria2 on
 -- tb_categoria2.id_categoria2 = tb_produto3.fk_categoria2_fk_produto3