-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 20:48:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_construindo_a_nossa_vida
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_construindo_a_nossa_vida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_construindo_a_nossa_vida` DEFAULT CHARACTER SET utf8 ;
USE `db_construindo_a_nossa_vida` ;

-- -----------------------------------------------------
-- Table `db_construindo_a_nossa_vida`.`tb_cat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_construindo_a_nossa_vida`.`tb_cat` ;

CREATE TABLE IF NOT EXISTS `db_construindo_a_nossa_vida`.`tb_cat` (
  `id_cat` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NOT NULL,
  PRIMARY KEY (`id_cat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_construindo_a_nossa_vida`.`tb_produtol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_construindo_a_nossa_vida`.`tb_produtol` ;

CREATE TABLE IF NOT EXISTS `db_construindo_a_nossa_vida`.`tb_produtol` (
  `id_loja` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NULL,
  `fk_produtos` INT NOT NULL,
  PRIMARY KEY (`id_loja`),
  INDEX `fk_tb_produtol_tb_cat_idx` (`fk_produtos` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtol_tb_cat`
    FOREIGN KEY (`fk_produtos`)
    REFERENCES `db_construindo_a_nossa_vida`.`tb_cat` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- select  *from tb_cat
INSERT INTO `db_construindo_a_nossa_vida`.`tb_cat` (`tipo`, `ativo`) VALUES ('Construção', true);
INSERT INTO `db_construindo_a_nossa_vida`.`tb_cat` (`tipo`, `ativo`) VALUES ('Hidráulico', false);
INSERT INTO `db_construindo_a_nossa_vida`.`tb_cat` (`tipo`, `ativo`) VALUES ('Elétrico', false);
-- select * from tb_produtol
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produtol` (`nome`, `marca`, `valor`, `fk_produtos`) VALUES ('Cimento', 'Votoran', '50.00', '1');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produtol` (`nome`, `marca`, `valor`, `fk_produtos`) VALUES ('Cerâmica', 'POrtello', '40.00', '1');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produtol` (`nome`, `marca`, `valor`, `fk_produtos`) VALUES ('Areia', 'Amanco', '100.00', '1');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produtol` (`nome`, `marca`, `valor`, `fk_produtos`) VALUES ('Luva', 'Tigre', '5.00', '2');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produtol` (`nome`, `marca`, `valor`, `fk_produtos`) VALUES ('Tubos pvc', 'Amanco', '10.00', '2');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produtol` (`nome`, `marca`, `valor`, `fk_produtos`) VALUES ('Ralo', 'Quartolit', '50.00', '2');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produtol` (`nome`, `marca`, `valor`, `fk_produtos`) VALUES ('Fio', 'Portello', '30', '3');
INSERT INTO `db_construindo_a_nossa_vida`.`tb_produtol` (`nome`, `marca`, `valor`, `fk_produtos`) VALUES ('Disjuntor', 'Tigre', '80', '3');
-- select * from tb_produtol where valor > 50
-- select * from tb_produtol where valor BETWEEN 3 and 60
-- select * from tb_produlol where nome like 'c' 
-- select *  from tb_produtol inner join tb_cat on tb_produtol.fk_produtos = tb_cat.id_cat
-- select * from tb_produtol inner join tb_cat on tb_produtol.fk_produtos= tb_cat.id_cat where tb_cat.cat = "Hidráulica"