-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 21:22:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cursoDaMinhaVida
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cursoDaMinhaVida
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cursoDaMinhaVida` DEFAULT CHARACTER SET utf8 ;
USE `db_cursoDaMinhaVida` ;

-- -----------------------------------------------------
-- Table `db_cursoDaMinhaVida`.`tb_cat1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cursoDaMinhaVida`.`tb_cat1` ;

CREATE TABLE IF NOT EXISTS `db_cursoDaMinhaVida`.`tb_cat1` (
  `id_cat1` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NOT NULL,
  PRIMARY KEY (`id_cat1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cursoDaMinhaVida`.`tb_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cursoDaMinhaVida`.`tb_curso` ;

CREATE TABLE IF NOT EXISTS `db_cursoDaMinhaVida`.`tb_curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Periodo` VARCHAR(45) NOT NULL,
  `Valor` VARCHAR(45) NULL,
  `fk_curso` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_tb_curso_tb_cat1_idx` (`fk_curso` ASC) VISIBLE,
  CONSTRAINT `fk_tb_curso_tb_cat1`
    FOREIGN KEY (`fk_curso`)
    REFERENCES `db_cursoDaMinhaVida`.`tb_cat1` (`id_cat1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO `db_cursodaminhavida`.`tb_cat1` (`tipo`, `ativo`) VALUES ('Graduação', true);
INSERT INTO `db_cursodaminhavida`.`tb_cat1` (`tipo`, `ativo`) VALUES ('Pós-Graduação', true);
INSERT INTO `db_cursodaminhavida`.`tb_cat1` (`tipo`, `ativo`) VALUES ('Técnico', false);
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`nome`, `Periodo`, `Valor`, `fk_curso`) VALUES ('Letras', 'Noturno', '700.00', '1');
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`nome`, `Periodo`, `Valor`, `fk_curso`) VALUES ('Java', 'Integral', '500.00', '3');
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`nome`, `Periodo`, `Valor`, `fk_curso`) VALUES ('PHP', 'Noturno', '200.00', '3');
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`nome`, `Periodo`, `Valor`, `fk_curso`) VALUES ('Ingles', 'Matutino', '800.00', '2');
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`nome`, `Periodo`, `Valor`, `fk_curso`) VALUES ('História', 'Vespertino', '200.00', '1');
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`nome`, `Periodo`, `Valor`, `fk_curso`) VALUES ('Enfermagem', 'Integral', '900.00', '3');
INSERT INTO `db_cursodaminhavida`.`tb_curso` (`nome`, `Periodo`, `Valor`, `fk_curso`) VALUES ('Jornalismo', 'Noturno', '90.00', '2');
-- select * from tb_curso
-- select * from tb_curso where valor > 50
-- select * from tb_curso where valor between 50 and 1000
-- select * from tb_curso inner join tb_cat1 on tb_curso.fk_curso = tb_cat1.id_cat1
-- select * from tb_curso inner join tb_cat1 on tb_curso.fk_curso = tb_cat1.id_cat1 where tb_cat1.tipo = "Graduação"