-- MySQL Script generated by MySQL Workbench
-- Thu Apr 22 18:32:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_farmacia_do_bem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_farmacia_do_bem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_farmacia_do_bem` DEFAULT CHARACTER SET utf8 ;
USE `db_farmacia_do_bem` ;

-- -----------------------------------------------------
-- Table `db_farmacia_do_bem`.`tb_categoria1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_farmacia_do_bem`.`tb_categoria1` ;

CREATE TABLE IF NOT EXISTS `db_farmacia_do_bem`.`tb_categoria1` (
  `id_categoria1` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NOT NULL,
  PRIMARY KEY (`id_categoria1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_farmacia_do_bem`.`tb_produto1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_farmacia_do_bem`.`tb_produto1` ;

CREATE TABLE IF NOT EXISTS `db_farmacia_do_bem`.`tb_produto1` (
  `id_produto1` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Valor` DECIMAL NOT NULL,
  `codigo_produto` INT(5) NOT NULL,
  `id_cat` INT NOT NULL,
  PRIMARY KEY (`id_produto1`),
  INDEX `fk_tb_produto1_tb_categoria1_idx` (`id_cat` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto1_tb_categoria1`
    FOREIGN KEY (`id_cat`)
    REFERENCES `db_farmacia_do_bem`.`tb_categoria1` (`id_categoria1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `db_farmacia_do_bem`.`tb_categoria1` (`tipo`, `ativo`) VALUES ('Remedio', true);
INSERT INTO `db_farmacia_do_bem`.`tb_categoria1` (`tipo`, `ativo`) VALUES ('Produtos de beleza', false);
INSERT INTO `db_farmacia_do_bem`.`tb_categoria1` (`tipo`, `ativo`) VALUES ('Produtos variados', false);

INSERT INTO `db_farmacia_do_bem`.`tb_produto1` (`Nome`, `Valor`, `codigo_produto`, `id_cat`) VALUES ('Dorflex', '2.0', '001111', '1');
INSERT INTO `db_farmacia_do_bem`.`tb_produto1` (`Nome`, `Valor`, `codigo_produto`, `id_cat`) VALUES ('Protetor solar', '70.00', '033444', '3');
INSERT INTO `db_farmacia_do_bem`.`tb_produto1` (`Nome`, `Valor`, `codigo_produto`, `id_cat`) VALUES ('Ritalina', '60.00', '333333', '1');
INSERT INTO `db_farmacia_do_bem`.`tb_produto1` (`Nome`, `Valor`, `codigo_produto`, `id_cat`) VALUES ('Desodorante', '15.00', '22345555', '3');
INSERT INTO `db_farmacia_do_bem`.`tb_produto1` (`Nome`, `Valor`, `codigo_produto`, `id_cat`) VALUES ('Chocolate', '2.00', '45678', '3');
INSERT INTO `db_farmacia_do_bem`.`tb_produto1` (`Nome`, `Valor`, `codigo_produto`, `id_cat`) VALUES ('Ziagen', '90.00', '5541', '1');
INSERT INTO `db_farmacia_do_bem`.`tb_produto1` (`Nome`, `Valor`, `codigo_produto`, `id_cat`) VALUES ('Salgadinho', '5.00', '12345', '3');
INSERT INTO `db_farmacia_do_bem`.`tb_produto1` (`Nome`, `Valor`, `codigo_produto`, `id_cat`) VALUES ('Orencia', '80.00', '090909', '1');
 -- select * from tb_produto1 where valor >50
 -- select *from tb_produto1 where valor >=3 and valor <=60
-- select * from tb_produto1 where  nome like "%b"
-- select tb_categoria1.tipo, tb_categoria1.ativo, tb_produto1.nome, tb_produto1.valor, tb_produto1.codigo_produto from tb_produto1 inner join tb_categoria1 on tb_categoria1.id_categoria1= tb_produto1.id_cat
-- select tb_categoria1.tipo, tb_categoria1.ativo, tb_produto1.nome, tb_produto1.valor, tb_produto1.codigo_produto from tb_produto1 inner join tb_categoria1 on tb_categoria1.id_categoria1= tb_produto1.id_cat where tb_categoria1.tipo = "Produtos variados"